# Default state for all rules
default: true

# allow long lines for tables and code blocks
MD013:
  code_blocks: false
  tables: false

# Allow same headers for non-siblings, e. g. in the CHANGELOG
MD024:
  siblings_only: true
