include:
  - ./oats-template.yml
input:
  - path: /api/HttpClient/Get
expected:
  logs:
    - logql: '{service_name="unknown_service:dotnet"} |~ `Application started.`'
      contains:
        - 'Application started'
  traces:
    - traceql: '{ span.http.route =~ "api/HttpClient/Get" }'
      spans:
        - name: 'GET api/HttpClient/Get'
          attributes:
            service.name: aspnetcore
            service.version: 1.0.0.0
            telemetry.distro.name: grafana-opentelemetry-dotnet
            telemetry.distro.version: regex:.+
            deployment.environment: production
            process.runtime.description: regex:.NET.+
            process.runtime.name: .NET
            process.runtime.version: regex:.+
            host.name: regex:.+
            telemetry.sdk.name: opentelemetry
            telemetry.sdk.language: dotnet
            telemetry.sdk.version: regex:.+
    - traceql: '{ resource.process.pid > 0 }'
      spans:
        - name: 'GET'
