matrix:
  - name: default
    docker-compose:
      generator: lgtm
      files:
        - ../docker-compose.oats.yml
  - name: self-contained
    docker-compose:
      generator: lgtm
      files:
        - ../docker-compose.self-contained.oats.yml
interval: 500ms
