docker-compose:
  generator: lgtm
  files:
    - ../docker-compose.oats.yml
input:
  - path: /api/HttpClient/Get
interval: 500ms
expected:
  traces:
    - traceql: '{ name =~ "api/HttpClient/Get" }'
      spans:
        - name: 'GET'
          attributes:
            http.request.method: GET
  metrics:
    - promql: http_client_request_duration_count{http_request_method="GET", http_response_status_code="200"}
      value: '>= 0'
