include:
  - ./oats-template.yml
input:
  - path: /api/HttpClient/GetError
expected:
  traces:
    - traceql: '{ name =~ "api/HttpClient/GetError" }'
      spans:
        - name: 'GET'
          attributes:
            error.type: '500'
            http.request.method: GET
  metrics:
    - promql: http_client_request_duration_count{}
      value: '>= 0'
