include:
  - ./oats-template.yaml
input:
  - path: /api/HttpClient/Get
expected:
  traces:
    - traceql: '{ span.http.route =~ "api/HttpClient/Get" }'
      spans:
        - name: 'GET api/HttpClient/Get'
          attributes:
            http.request.method: GET
  metrics:
    - promql: http_client_request_duration_count{http_request_method="GET", http_response_status_code="200"}
      value: '>= 0'
