include:
  - ./oats-template.yaml
input:
  - path: /api/HttpClient/GetError
expected:
  traces:
    - traceql: '{ span.http.route =~ "api/HttpClient/GetError" }'
      spans:
        - name: 'GET api/HttpClient/GetError'
          attributes:
            error.type: '500'
            http.request.method: GET
  metrics:
    - promql: http_client_request_duration_seconds_count{}
      value: '>= 0'
