services:
  aspnetcore:
    image: ${DOCKER_REGISTRY-}aspnetcore
    build:
      context: ../..
      dockerfile: examples/net10.0/aspnetcore/Dockerfile
      args:
        DOTNET_PUBLISH_ARGS: "/p:BuildDistroFromSource=${BUILD_DISTRO_FROM_SOURCE:-true}"
    depends_on:
      - redis
      - mssql
    ports:
      - "8080:8080" # for OATs
    environment:
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL_S3=http://localstack:4566
      - OTEL_BLRP_SCHEDULE_DELAY=5000
      - OTEL_BSP_SCHEDULE_DELAY=5000
      - OTEL_METRIC_EXPORT_INTERVAL=5000
  redis:
    image: redis:8.8.0@sha256:8c1a48e2f0a32acc27ae5a292bc8a0ce3f6f1d1b4a124e0fd1344b9ecf1ec3ae
    ports:
      - "6379:6379"
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:2cd0aec4a3bfc3cf9205bed3f7922f4c6208f7c767dc62edcee308d0fd7d56d0
    ports:
      - "1433:1433"
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password12345%%
  localstack:
    image: localstack/localstack:4.14.0@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
