services:
  aspnetcore:
    image: ${DOCKER_REGISTRY-}aspnetcore
    build:
      context: ../..
      dockerfile: examples/net10.0/aspnetcore/Dockerfile
      args:
        DOTNET_PUBLISH_ARGS: "--self-contained true /p:PublishSingleFile=true /p:BuildDistroFromSource=${BUILD_DISTRO_FROM_SOURCE:-true}"
    entrypoint: ./aspnetcore
    environment:
      - AWS_ACCESS_KEY_ID=floci
      - AWS_SECRET_ACCESS_KEY=floci
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL_S3=http://floci:4566
      - OTEL_BLRP_SCHEDULE_DELAY=5000
      - OTEL_BSP_SCHEDULE_DELAY=5000
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4317
      - OTEL_METRIC_EXPORT_INTERVAL=5000
    ports:
      - "5000:8080"
      - "8080:8080" # for OATs
    depends_on:
      - redis
      - mssql
  redis:
    image: redis:8.10.1@sha256:691577adaf11927f4bb8871d40a5dd69a5c300d4453b742e8f6383c3e6e8d2e1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:4bab24f36c1ecd48e85f7d37df26e6bf301641d84c3fe652f9a0dcc947d512e1
    ports:
      - "1433:1433"
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Password12345%%
  floci:
    image: floci/floci:1.7.0@sha256:bec9b9f749322444a57fb0f00d3e007ffd49015162361aab84ccecd9b4f5f8ed
    ports:
      - "4510-4559:4510-4559"
      - "4566:4566"
