include:
  - ./oats-template.yml
input:
  - path: /api/MsSql/Tables
expected:
  traces:
    - traceql: '{ span.http.route =~ "api/MsSql/Tables"}'
      spans:
        - name: 'master'
          attributes:
            db.system: mssql
            db.name: master
            otel.library.name: OpenTelemetry.Instrumentation.SqlClient
