include:
  - ./oats-template.yml
input:
  - path: /api/MsSql/ServerInfo
expected:
  traces:
    - traceql: '{ span.http.route =~ "api/MsSql/ServerInfo"}'
      spans:
        - name: 'master'
          attributes:
            db.system: mssql
            db.name: master
            db.statement: sp_server_info
            otel.library.name: OpenTelemetry.Instrumentation.SqlClient
