include:
  - ./oats-template.yml
input:
  - path: /api/MsSql/Tables
expected:
  traces:
    - traceql: '{ name =~ "api/MsSql/Tables"}'
      spans:
        - name: 'master'
          attributes:
            db.system: mssql
            db.name: master
            #db.statement: sp_server_info
            #db.statement_type: Text
            otel.library.name: OpenTelemetry.Instrumentation.SqlClient
