docker-compose:
  generator: lgtm
  files:
    - ../docker-compose.oats.yml
input:
  - path: /api/HttpClient/GetError
interval: 500ms
expected:
  traces:
    - traceql: '{ name =~ "api/HttpClient/GetError" }'
      spans:
        - name: 'GET'
          attributes:
            error.type: '500'
            http.request.method: GET
  metrics:
    - promql: http_client_request_duration_count{}
      value: '>= 0'
