docker-compose:
  generator: lgtm
  files:
    - ./docker-compose.oats.yml
input:
  - path: /api/HttpClient/Get
expected:
  traces:
    - traceql: '{ name =~ "api/HttpClient/Get" }'
      spans:
        - name: 'HTTP GET'
          attributes:
            http.method: GET
  metrics:
    - promql: http_client_duration_count{}
      value: '>= 0'
