name: dotnet format

on:
  push:
    branches: [ 'main*' ]
    paths:
    - '**.cs'
    - '.editorconfig'
  pull_request:
    paths:
    - '**.cs'
    - '.editorconfig'

jobs:
  check-format:
    runs-on: windows-2025
    permissions: {}

    steps:

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        filter: 'tree:0'
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: Run dotnet format
      run: dotnet format --verify-no-changes
