name: lint

on:
  pull_request:
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  lint:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 2
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Determine changed Markdown files
      id: changed-markdown
      run: |
        if [ "${GITHUB_EVENT_NAME}" = "pull_request" ] && \
          ! git diff --name-only --diff-filter=d 'HEAD^1' HEAD | grep -qiE '\.md$'; then
          echo "No Markdown files changed; Markdown linting will be skipped."
          echo "changed=false" >> "${GITHUB_OUTPUT}"
        else
          echo "changed=true" >> "${GITHUB_OUTPUT}"
        fi

    - name: Add actionlint problem matcher
      run: echo "::add-matcher::.github/actionlint-matcher.json"

    - name: Lint workflows
      uses: grafana/grafana-github-actions/actionlint@dff5d93ed96d0ebc7022b7eb28b6a6fa638e0dc0 # actionlint/v1.7.11
      with:
        args: -color

    - name: Lint markdown
      if: steps.changed-markdown.outputs.any-changed == 'true'
      uses: DavidAnson/markdownlint-cli2-action@6bf21b07787794f89a243495939cd651942aeabe # v24.1.0
      with:
        config: '.markdownlint.yaml'
        globs: |
          **/*.md

    - name: Install markdown-link-check
      if: steps.changed-markdown.outputs.changed == 'true'
      env:
        # renovate: datasource=npm depName=markdown-link-check packageName=markdown-link-check
        MARKDOWN_LINK_CHECK_VERSION: 3.14.2
      run: sudo npm install -g "markdown-link-check@${MARKDOWN_LINK_CHECK_VERSION}"

    - name: Check markdown links
      if: steps.changed-markdown.outputs.changed == 'true'
      run: "find . -name '*.md' -print0 | xargs -0 -n1 markdown-link-check --config .markdown_link_check_config.json"
