name: OATS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:

  package:
    runs-on: ubuntu-24.04

    steps:

    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: Build NuGet packages
      run: dotnet build --configuration Release

    - name: Publish NuGet packages
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: oats-packages
        path: ./artifacts/package/release
        if-no-files-found: error

  acceptance-tests:
    runs-on: ubuntu-24.04
    needs: package
    timeout-minutes: 20

    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          filter: 'tree:0'
          persist-credentials: false
          show-progress: false

      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: oats-packages
          path: ./.packages

      - name: Set up OATS and gcx
        uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5

      - name: Run acceptance tests
        env:
          BUILD_DISTRO_FROM_SOURCE: false
        run: mise run acceptance-test

      - name: Upload log file
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: docker-compose.log
          path: oats/yaml/build/**/output.log
          if-no-files-found: ignore
